version: '3.8'

services:
  web:
    build: ./src
    command: |
     bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://sa:pa$$w0rd30@db:5432/score_typer_dev
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=pa$$w0rd30
      - POSTGRES_DB=score_typer_dev

volumes:
  postgres_data: